name: "Push to Cachix"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: willruggiano
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: >
          for t in $(nix flake show --json | jq '.packages."x86_64-linux" | to_entries[].key'); do
            echo "Building $t..."
            nix build --json ".#$t" | jq -r '.[].outputs | to_entries[].value' | cachix push willruggiano
            echo "Building $t... done."
          done
      - run: echo "OK"
